#- hosts: "{{ env_host }}"
- hosts: rstudioRH7 
  vars:  
    custom_repo: true
  vars_files:
    - ~/RHACCOUNT
  become: yes
  become_method: sudo
  pre_tasks:
    - debug:
        msg: "Variables: _uid = {{ _uid }}, _pwd = **********"
#       msg: "Variables: _uid = {{ _uid }}, _pwd = {{ _pwd }}"
    - name: register RHEL8.6
      command: "/usr/bin/subscription-manager register --username {{ _uid }} --password {{ _pwd }} --auto-attach --force"
      when: _uid != "" and _pwd != ""
#     command: "/usr/bin/subscription-manager register --username <name> --password <password> --auto-attach"
    - name: register RHEL7 repo
      command: "/usr/bin/subscription-manager repos --enable=rhel-8-server-rpms --enable=rhel-8-server-extras-rpms --enable=rhel-8-server-optional-rpms"
    - name: register RHEL7 RHSCL Repo
      shell: "/usr/bin/subscription-manager repos --enable=rhel-server-rhscl-8-rpms"
    - name: register RHEL7 DevTools
      shell: "/usr/bin/subscription-manager repos --enable=rhel-8-server-devtools-rpms"
    - name: list RHEL enabled repos
      shell: "/usr/bin/subscription-manager repos --list-enabled"
      register: enabled_repos
    - debug:
        msg: "RHEL Enabled Repos: {{ enabled_repos }}" 
# tasks:
#   - name: download epel
#     shell:  wget https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm -O /tmp/epel-release-latest-8.noarch.rpm   
#   - name: Install epel
#     shell:  yum -y localinstall /tmp/epel*rpm
#
#   - name: Install python-pip
#     shell: yum install -y python27 python-pip

#   - name: install gdown
#     shell: pip install gdown  
#     yum:
#       name: python27-python-pip
#       state: latest

#   - name: Install python 3.6 and pip
#     shell: yum install -y python36 python36-pip
#   - name: Install bash autocomplete
#     shell: yum install -y bash-completion bash-completion-extras

#   - name: enable scl
#     become: yes
#     become_method: sudo
#     shell: scl enable python27 bash
#   - name: install gdown
#     shell: /opt/rh/python27/root/usr/bin/pip install gdown

#     Already secure copy to destination host
#   - name: use gdown to download and build local repo
#     shell: gdown https://drive.google.com/uc?id=1qaZH9_SrGyjHjWT3P2WtvZAhEkP9YG1Z -O /tmp/ancilRH7_repo.tar.gz

#     shell: gdown https://drive.google.com/uc?id=139Z0MfyT0WVWIzP_uwM2KxPCrfYs_vUV
#   - name: Install pip
#     easy_install:
#       name: pip
#       state: latest
#   - name: Build custom local repo
#      shell: wget https://drive.google.com/open?id=1qaZH9_SrGyjHjWT3P2WtvZAhEkP9YG1Z /tmp

#   - name: Extract repo to destination point
#     shell:  tar xvf /tmp/ancilRH7_repo.tar.gz -C /opt/ancillary_local
#   - name: Extract OpenOffice 4.1.6 
#     shell:  tar xvf /opt/ancillary_local/Apache_OpenOffice_4.1.6_Linux_x86-64_install-rpm_en-US.tar.gz -C /opt/ancillary_local/OO416 
#   - name: install bz2
#     yum:
#       name: bzip2

#   - name: install createrepo
#     yum:
#       name: createrepo
#       state: latest
#   - name: create local repo 
#     shell: createrepo /opt/ancillary_local/OO416
#     shell: createrepo /opt/devrepo-master/Packages
#   - name: create local repo file with updated link
#     file:
#       path: /etc/yum.repos.d/local.repo
#       state: touch
#       mode: "u=rw,g=r,o=r" 
#   - name: edit local.repo file
#     shell: |
#       echo '[localrepo]
#       name=localrepo
#       baseurl=file:///opt/ancillary_local/OO416
#       enabled=1
#       gpgcheck=0' >> /etc/yum.repos.d/local.repo
  roles:
#   - umask
    - epel8
    - devtoolsj
    - r_RH8
    - r-studio-desktopRH8
    - r-studio-serverRH8
    - r-studio-server-configRH8
    - r-shinyRH8
    - r-shiny-configRH8

  post_tasks:
#   - name: remove RHEL8.6
#     command:  "/usr/bin/subscription-manager remove --all"
#   - name: unregister RHEL7.5
#     command:  "/usr/bin/subscription-manager unregister"
#   - name: clean RHEL7.5
#     command:  "/usr/bin/subscription-manager clean"
